apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: manual-ducati-monster-1100
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/suetema/manual-ducati-monster-1100
